### ISSUE TITLE
How to get find the 'data' module

### ISSUE THREAD

**Issue by jsuit** [szagoruyko/loadcaffe#11]
I'm trying to load the bvlc_reference_caffenet model. It loads the model but I get this error message:
I get this message: 

MODULE data UNDEFINED
module 'data' not found

I'm assuming it is talking about not being able to find the dataset.

So my first question, is (1) is this message saying that it cant' find the dataset? Secondly, and more importantly, how do I fix this?

**Comment by szagoruyko** [comment]
no, it's not the dataset, it's an abstract definition of input *data* in caffe.
so this message you see is just a warning a can be ignored.
