### ISSUE TITLE
TanH layer

### ISSUE THREAD

**Issue by Jeongseob** [szagoruyko/loadcaffe#12]
Hi,

I have one question about loadcaffe module. It seems like that TanH layer, which is one of the neuron layers, is not implemented in loadcaffe. Actually, I am not an expert for Torch and not familiar with the infrastructure. If I would like to add the TanH layer in loadcaffe module, how can I apply my custom module to torch? Could you give me a brief instruction how to insert the module into Torch?

**Comment by szagoruyko** [comment]
I have added Tanh and Sigmoid in bc14401f22c5600a14d0f630531e0b94bf7576cc. it's nn.Sigmoid and nn.Tanh
