### ISSUE TITLE
module 'mnist'  not found

### ISSUE THREAD

**Issue by meteora9479** [szagoruyko/loadcaffe#16]
I ran the example and loaded the mnist model, but

Successfully loaded /home/yusheng/workspace/caffe/examples/mnist/lenet_iter_10000.caffemodel
Out[2]:
module 'mnist' not found
Out[2]:
conv1: 20 1 5 5
Out[2]:
conv2: 50 20 5 5
Out[2]:
ip1: 1 1 800 500
Out[2]:
ip2: 1 1 500 10

what does the "module" mean ?

Eventually, when I ran this line "net:forward(images[1]:view(1,28,28)):max(1)" and it crashed

.../workspace/torch/install/share/lua/5.1/nn/Sequential.lua:39: bad argument #1 (field padding does not exist)
stack traceback:
    [C]: in function 'updateOutput'
    .../workspace/torch/install/share/lua/5.1/nn/Sequential.lua:39: in function 'forward'
    [string "_,y = net:forward(images[1]:view(1,28,28)):ma..."]:1: in main chunk
    [C]: in function 'xpcall'
    ...ng/workspace/torch/install/share/lua/5.1/itorch/main.lua:177: in function <...ng/workspace/torch/install/share/lua/5.1/itorch/main.lua:143>
    ...ng/workspace/torch/install/share/lua/5.1/lzmq/poller.lua:75: in function 'poll'
    ...workspace/torch/install/share/lua/5.1/lzmq/impl/loop.lua:307: in function 'poll'
    ...workspace/torch/install/share/lua/5.1/lzmq/impl/loop.lua:325: in function 'sleep_ex'
    ...workspace/torch/install/share/lua/5.1/lzmq/impl/loop.lua:370: in function 'start'
    ...ng/workspace/torch/install/share/lua/5.1/itorch/main.lua:344: in main chunk
    [C]: in function 'require'
    [string "arg={'/home/yusheng/.ipython/profile_torch/se..."]:1: in main chunk

Could you help me solve this problem ?

**Comment by szagoruyko** [comment]
```module 'mnist' not found``` is just a warning. You have to update nn and cunn to get rid of the padding error:
```
luarocks install nn
luarocks install cunn
```

**Comment by meteora9479** [comment]
I've updated and worked , but

Successfully loaded /home/yusheng/workspace/caffe/examples/mnist/lenet_iter_10000.caffemodel
module 'mnist' not found
conv1: 20 1 5 5
conv2: 50 20 5 5
ip1: 1 1 800 500
ip2: 1 1 500 10
ConfusionMatrix:
[[     972       0       0       0       0       0       3       1       4       0]   99.184%
 [       0    1131       1       1       0       0       1       1       0       0]   99.648%
 [       0       1    1025       1       1       0       0       1       3       0]   99.322%
 [       0       0       1    1001       0       4       0       1       3       0]   99.109%
 [       0       0       1       0     977       0       2       0       0       2]   99.491%
 [       2       0       0       8       0     880       1       0       1       0]   98.655%
 [       3       1       0       1       3       4     945       0       1       0]   98.643%
 [       0       3       7       2       0       0       0    1016       0       0]   98.833%
 [       3       0       2       0       0       2       0       1     964       2]   98.973%
 [       1       0       0       5       5       3       1       2       3     989]]  98.018%
 + average row correct: 98.987424373627%
 + average rowUcol correct (VOC measure): 97.996342182159%
 + global correct: 99%

Can I ignore "module 'mnist' not found" this warning ?

**Comment by szagoruyko** [comment]
yes you can ignore it.
