### ISSUE TITLE
unable to load bvlc_googlenet

### ISSUE THREAD

**Issue by zhfe99** [szagoruyko/loadcaffe#18]
I am able to load AlexNet and VGGNet without problem.

But when I tried to load googlenet, I encountered the following errors:

```
...ave/imgnet/caffe/proto/imgnet_v2_goo_deploy.prototxt.lua:64: attempt to call method '
ceil' (a nil value)                                                                    
stack traceback:
        ...ave/imgnet/caffe/proto/imgnet_v2_goo_deploy.prototxt.lua:64: in main chunk
```

I check line 64 of the generated "*.prototxt.lua", which is:
`table.insert(model, {'loss1/ave_pool', nn.SpatialAveragePooling(5, 5, 3, 3):ceil()})`

It seems the function `ceil()` is undefined in `nn.SpatialAveragePooling`

**Comment by szagoruyko** [comment]
loadcaffe doesn't work with googlenet, supported networks are in the table in README.md.
googlenet in torch format and better accuracy then Caffe model will be posted in Torch Model Zoo sometime soon.

**Comment by Code-Deep-Blue** [comment]
Has there been any followup on getting a Torch pretrained Googlenet? Can't seem to find it in the Model Zoo (or anywhere else for that matter)

**Comment by szagoruyko** [comment]
@Code-Deep-Blue check https://github.com/soumith/inception.torch https://github.com/Moodstocks/inception-v3.torch
