### ISSUE TITLE
Same model, different outputs

### ISSUE THREAD

**Issue by jsuit** [szagoruyko/loadcaffe#19]
I load up a model, like this:
data = torch.randn(128,3,224,224)*255
data=data:cuda()
model1 = loadcaffe(....., 'ccn2')
model2 = nn.Sequential()
stopLayer = 12
for i=1, stopLayer do
     model2:add(model1.modules[i]:clone()
end
model2:cuda()
model1:forward(data)
model2:forward(data)
print(model1.modules[stopLayer].output:mean())
print(model2.modules[stopLayer.output:mean())

Why are very different numbers printed to the screen?

**Comment by szagoruyko** [comment]
try to add ```model:evaluate()``` to both, by default the models are loaded in train mode.

**Comment by jsuit** [comment]
I've done that and it doesn't help. Secondly, I'm stopping it before it hits a dropout layer. (the stopLayer is before a dropout layer). Secondly, I'm using the model "bvlc_reference_caffenet".

**Comment by jsuit** [comment]
Another thing I noticed is that if I copy over stopLayer+1 and then look at the outputs of stopLayer, I get the same answer.

**Comment by jsuit** [comment]
It also strikes me as odd that for every layer that has weights, the min of the weights is always 0 for the "bvlc_reference_caffenet" model.

**Comment by fmassa** [comment]
Maybe you are stopping just before a a ReLU layer, which is by default in place, and it's overwriting your previous output ?

**Comment by jsuit** [comment]
that is it!
