### ISSUE TITLE
Could not load model

### ISSUE THREAD

**Issue by LijieTu** [szagoruyko/loadcaffe#20]
Maybe it is some trivial setting but I could not load the model at all.
The following is from https://github.com/szagoruyko/loadcaffe/blob/master/examples/mnist_lenet.lua

I see here "
```
prototxt = '/opt/caffe/examples/mnist/lenet.prototxt'
binary = '/opt/caffe/examples/mnist/lenet_iter_10000.caffemodel'
```

It seems I must have caffe installed in `/opt/` dir?
Or maybe there is an easy way to download all models  to `/opt/caffe/ `?
Thank you.

**Comment by szagoruyko** [comment]
you don't need to have caffe installed, just download 2 files `deploy.prototxt` and `*.caffemodel`, the links are in their model zoo. Then you need to provide the paths to them.

**Comment by LijieTu** [comment]
Thanks. I just put the files in the path and it works!
