### ISSUE TITLE
Unable to load 'Age&Gender' and 'Network-in-Network Imagenet'

### ISSUE THREAD

**Issue by GitHubSGN** [szagoruyko/loadcaffe#22]
Hi, when I tried to load 'Age&Gender', I encountered the following errors:

MODULE data UNDEFINED
warning: module 'data [type 5]' not found
.../torch/install/bin/luajit: ...age_gender_models_and_data.0.0.1/deploy_age.prototxt.lua:8: attempt to call method 'ceil' (a nil value)

The 8th line of deploy_age.prototxt.lua is 
table.insert(model, {'pool1', nn.SpatialMaxPooling(3, 3, 2, 2, 0, 0):ceil()})

and, when I loaded the 'Network-in-Network Imagenet', the similar error occurs:

MODULE data UNDEFINED
warning: module 'data [type 5]' not found
.../torch/install/bin/luajit: train_val.prototxt.lua:12: attempt to call method 'ceil' (a nil value)

the 12th line of train_val.prototxt.lua is 
table.insert(model, {'pool1', nn.SpatialMaxPooling(3, 3, 2, 2, 0, 0):ceil()})

It seems that the function ceil() cannot be used in nn.SpatialMaxPooling?Thank you.

**Comment by szagoruyko** [comment]
Hi, update your nn and cunn, it was added a few months ago
