### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by sublee** [szagoruyko/loadcaffe#23]
I can't install this project via LuaRocks:

```console
$ luarocks install loadcaffe --local

Error: No results matching query were found.
```

Is there an alternative way?

**Comment by szagoruyko** [comment]
make sure you are using torch luarocks. loadcaffe is there.

**Comment by sublee** [comment]
Oh, it works.  I'm sorry.

**Comment by sublee** [comment]
It looks like to work but now I have another installation error:

```
Error: Failed installing dependency: https://raw.githubusercontent.com/torch/roc
ks/master/ccn2-scm-1.rockspec - Failed installing dependency: https://raw.github
usercontent.com/torch/rocks/master/cutorch-scm-1.rockspec - Build error: Failed
building.
```

**Comment by cpury** [comment]
+1, and the actual error that happens is:

    CMake Error at /usr/local/Cellar/cmake/3.0.2/share/cmake/Modules/FindCUDA.cmake:568 (message):
      Specify CUDA_TOOLKIT_ROOT_DIR
    Call Stack (most recent call first):
      CMakeLists.txt:7 (FIND_PACKAGE)

So it's trying to find CUDA even though I don't want to use it?

**Comment by szagoruyko** [comment]
It is installable without cuda, just fixed and checked that

**Comment by sublee** [comment]
Now I can install this without an error.  Thanks to fix the problem.
