### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by PaniniGelato** [szagoruyko/loadcaffe#26]
hi all,
I can't install via luaRocks,  
```
Error: No results matching query were found.
```
And got nothing on https://luarocks.org/search?q=loadRoffee&non_root=on

**Comment by szagoruyko** [comment]
install torch http://torch.ch

**Comment by PaniniGelato** [comment]
i've already installed torch follow by the guides.
And I can install other rocks list on http://luarocks.org:8080/m/root, but install loadcoffee failed with 'no results maching' 
Did I miss something?

**Comment by atomic** [comment]
You can install it manually by running 'luarocks install loadcaffe/loadcaffee-1.0.0.rockspec'.

**Comment by PaniniGelato** [comment]
@atomic @szagoruyko thank you for your help. I've solved the problem.

**Comment by harvimt** [comment]
@PaniniGelato How?

**Comment by harvimt** [comment]
ok you need to run torch-activate which is put in your ~/.profile automatically buy the torch installer.

**Comment by PaniniGelato** [comment]
@harvimt  I just followed atomic's guides to install it manually.

**Comment by dendisuhubdy** [comment]
Thank you @atomic that helped me

**Comment by maxko87** [comment]
For those still stuck, try:
`git clone git@github.com:szagoruyko/loadcaffe.git`
`~/torch/install/bin/luarocks install loadcaffe/loadcaffe-1.0-0.rockspec`

**Comment by jeremymarino** [comment]
Maxko87,

After entering in the command `git clone git@github.com:szagoruyko/loadcaffe.git`

the output reads (running as sudo)

`Cloning into 'loadcaffe'...
Warning: Permanently added the RSA host key for IP address '192.30.252.130' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
`

What else would you recommend?

**Comment by PaniniGelato** [comment]
@jeremymarino try https protocol instead of git

**Comment by ot6nyu** [comment]
@maxko87 Thank you this makes sense and worked perfectly!
