### ISSUE TITLE
Can't load a specific model

### ISSUE THREAD

**Issue by spinda** [szagoruyko/loadcaffe#31]
Using the following code:

```lua
require 'loadcaffe'
loadcaffe.load('models/VGG_ILSVRC_19_layers_deploy.prototxt','models/VGG_ILSVRC_19_layers.caffemodel','nn-cpu')
```

I'm unable to load the VGG-19 network from [`neural-style`](https://github.com/jcjohnson/neural-style)&mdash;output is:

```
Couldn't load models/VGG_ILSVRC_19_layers.caffemodel
```

This is using the `loadcaffe` version from `luarocks install loadcaffe`. I've also tried using the version on `master`, without success. (I'm on Ubuntu 15.04.)

The relevant files are here:
- [`models/VGG_ILSVRC_19_layers_deploy.prototxt`](http://b.1339.cf/mnigolt.prototxt)
- [`models/VGG_ILSVRC_19_layers.caffemodel`](http://b.1339.cf/qiwtrdg.caffemodel)

**Comment by szagoruyko** [comment]
do 'nn' instead of 'nn-cpu'

**Comment by spinda** [comment]
Unfortunately that produces the same result:

```lua
require 'loadcaffe'
loadcaffe.load('models/VGG_ILSVRC_19_layers_deploy.prototxt','models/VGG_ILSVRC_19_layers.caffemodel','nn')
```

```
Couldn't load models/VGG_ILSVRC_19_layers.caffemodel
```

**Comment by szagoruyko** [comment]
reproduced, will look into it when have time. meanwhile do
```lua
loadcaffe.load('VGG_ILSVRC_19_layers_deploy.prototxt','VGG_ILSVRC_19_layers.caffemodel','nn')
```
from 'models' folder

**Comment by spinda** [comment]
Same result, sadly:

```
neural-style ➜ cd models
models ➜ th
 
  ______             __   |  Torch7                                         
 /_  __/__  ________/ /   |  Scientific computing for Lua. 
  / / / _ \/ __/ __/ _ \  |  Type ? for help                                
 /_/  \___/_/  \__/_//_/  |  https://github.com/torch         
                          |  http://torch.ch                  
	
th> require 'loadcaffe'
true	
                                                                      [0.0160s]	
th> loadcaffe.load('VGG_ILSVRC_19_layers_deploy.prototxt','VGG_ILSVRC_19_layers.caffemodel','nn')
Couldn't load VGG_ILSVRC_19_layers.caffemodel
                                                                      [0.0094s]
```

**Comment by szagoruyko** [comment]
bizarre. check that your caffemodel is not corrupted, this is my md5:
```b5c644beabd7cf06bdd9065cfd674c97  VGG_ILSVRC_19_layers.caffemodel```
and copy paste ```VGG_ILSVRC_19_layers_deploy.prototxt.lua``` somewhere

**Comment by spinda** [comment]
Ah ha! Now I feel really silly. Running `md5sum VGG_ILSVRC_19_layers.caffemodel` shows that my copy was corrupted.

I downloaded the models originally using `wget`, and the first time, the connection was interrupted. It turns out that running `wget` again with a partially-complete file doesn't overwrite that file, it downloads to `VGG_ILSVRC_19_layers.caffemodel.1`. I'd used `md5sums models/*` to verify checksums before, but it seems that I was looking at the checksum for `VGG_ILSVRC_19_layers.caffemodel.1` instead of `VGG_ILSVRC_19_layers.caffemodel`.

Switching out `VGG_ILSVRC_19_layers.caffemodel` with a good copy fixes the issue.

Thank you, and sorry for taking up your time with this!

**Comment by hughperkins** [comment]
Hmmm, I've downloaded it 4 times, over a 19MB/s connection (ec2), and each time a different md5 checksum :-P

**Comment by soumith** [comment]
@hughperkins maybe that's just your country ;)

**Comment by hughperkins** [comment]
ec2 is North Virginia.

**Comment by soumith** [comment]
strange that on EC2 it'd be so unreliable. i'm surprised.

**Comment by hughperkins** [comment]
Yes.  odd..   I dont reckon its an ec2 issue.

**Comment by hughperkins** [comment]
Interestingly, if I download it to Tokyo, which is only 5.5MB/sec, it takes a bit longer, but hte checksum is correct htis time.

**Comment by hughperkins** [comment]
(ah, because out of diskspace :-P )
