### ISSUE TITLE
I received this problem after I run the mnist_lenet.lua

### ISSUE THREAD

**Issue by SalemAmeen** [szagoruyko/loadcaffe#42]
I received this problem after I run the mnist_lenet.lua

I read about this problem from previous issues and I tried to 

luarocks install nn
luarocks install cunn

But I still received this error please any help

(venv)sal@sal-All-Series:~/loadcaffe-master/examples$ th -i mnist_lenet.lua
/home/sal/torch/install/bin/luajit: /home/sal/torch/install/share/lua/5.1/trepl/init.lua:383: module 'mnist' not found:No LuaRocks module found for mnist
	no field package.preload['mnist']
	no file '/home/sal/.luarocks/share/lua/5.1/mnist.lua'
	no file '/home/sal/.luarocks/share/lua/5.1/mnist/init.lua'
	no file '/home/sal/torch/install/share/lua/5.1/mnist.lua'
	no file '/home/sal/torch/install/share/lua/5.1/mnist/init.lua'
	no file './mnist.lua'
	no file '/home/sal/torch/install/share/luajit-2.1.0-alpha/mnist.lua'
	no file '/usr/local/share/lua/5.1/mnist.lua'
	no file '/usr/local/share/lua/5.1/mnist/init.lua'
	no file '/home/sal/.luarocks/lib/lua/5.1/mnist.so'
	no file '/home/sal/torch/install/lib/lua/5.1/mnist.so'
	no file './mnist.so'
	no file '/usr/local/lib/lua/5.1/mnist.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'error'
	/home/sal/torch/install/share/lua/5.1/trepl/init.lua:383: in function 'require'
	mnist_lenet.lua:4: in main chunk
	[C]: in function 'dofile'
	.../sal/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670
(venv)sal@sal-All-Series:~/loadcaffe-master/examples$

**Comment by szagoruyko** [comment]
luarocks install mnist

**Comment by SalemAmeen** [comment]
WOW, Many thanks, works
