### ISSUE TITLE
Using loadcaffe with Caffe variants

### ISSUE THREAD

**Issue by JakeRyan1** [szagoruyko/loadcaffe#44]
Hi, What changes do I need to make in order to use loadcaffe with other caffe variants (e.g. https://github.com/torrvision/crfasrnn)

**Comment by szagoruyko** [comment]
first try to load with the current version, if fails or not all layers are there then copy caffe/src/proto/caffe.proto and try to compile with it, then add missing layer definitions to loadcaffe
