### ISSUE TITLE
Cannot install loadcaffe: "No results matching query were found"

### ISSUE THREAD

**Issue by blinry** [szagoruyko/loadcaffe#48]
What am I missing? On Arch Linux:

```
$ luarocks --version
/usr/sbin/luarocks 2.3.0
LuaRocks main command-line interface
$ lua -v
Lua 5.3.2  Copyright (C) 1994-2015 Lua.org, PUC-Rio
$ sudo luarocks install loadcaffe

Error: No results matching query were found.
```

**Comment by szagoruyko** [comment]
install torch first http://torch.ch/docs

**Comment by blinry** [comment]
I did install Arch Linux' [torch7-git](￼https://aur.archlinux.org/packages/torch7-git/) and [torch7-trepl-git](https://aur.archlinux.org/packages/torch7-trepl-git/) packages, which provide the libraries and the `th` binary. 

`sudo luarocks search --all` also does not list anything matching "loadcaffe". What else could I try? Do I need "luarocks for Lua 5.2/5.1 modules", maybe?

**Comment by szagoruyko** [comment]
torch maintains it's own rocks, make sure youre running luarocks from torch and not the system one.

**Comment by blinry** [comment]
Ah, I see. That's it, thanks! A .bashrc-modifying install script is a bit scary :]

**Comment by thistleknot** [comment]
I'm having the same issue, "No results matching query were found" I'm not exactly sure how to resolve it.  

I see @szagoruyko 's comment, but not sure how to run it using torch.  I tried running the command in torch but nothing happens.

**Comment by thistleknot** [comment]
Solved:

sudo :~/torch/install/bin/luarocks install loadcaffe

**Comment by szagoruyko** [comment]
@thistleknot very bad idea, you should not use sudo with torch luarocks. your bashrc is most probably broken.

**Comment by jmbh** [comment]
thisleknow suggested a solution, but i have not the slightest idea how to do this. could someone post the actual solution?

**Comment by jcklpe** [comment]
I've gotten a similar issue. Could this perhaps have something to do with running an alternative to bash? I'm using zsh and while it requested to add luarocks to path on my .zshrc it might have screwed something up and that's why it's not working. Thoughts?
