### ISSUE TITLE
Error in MNIST example

### ISSUE THREAD

**Issue by eladhoffer** [szagoruyko/loadcaffe#5]
Getting
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 7:7: Message type "caffe.NetParameter" has no field named "layer".

when running the mnist example.
Any ideas why?

**Comment by szagoruyko** [comment]
You're using a newer version of caffe where caffe.proto was updated to have this layer parameter

**Comment by sunilrao43** [comment]
@szagoruyko  can you help me parsing the caffemodel to my C code
thanks in advance

**Comment by ssakhavi** [comment]
@szagoruyko, what is the solution to this issue?

**Comment by szagoruyko** [comment]
@ssakhavi it seems that they change caffe without backward compatibility. I will take a look at what could be done.

**Comment by ssakhavi** [comment]
@szagoruyko Thanks

**Comment by ssakhavi** [comment]
I don't see the error anymore but the network is empty when loading. 
Why do you this is?

**Comment by szagoruyko** [comment]
for which network?

**Comment by ssakhavi** [comment]
MNIST

**Comment by szagoruyko** [comment]
so if it's a net saved with an up to date caffe loadcaffe won't work. I've fixed it to work with older nets from here https://github.com/BVLC/caffe/wiki/Model-Zoo

**Comment by szagoruyko** [comment]
fixed by https://github.com/szagoruyko/loadcaffe/pull/10
