### ISSUE TITLE
Can't install loadcaffe

### ISSUE THREAD

**Issue by ngryman** [szagoruyko/loadcaffe#51]
Hi,

I'm totally newbie to `lua`.
I'm trying to install `loadcaffe` as mentioned in the `readme`.
I have OS X El Captain.

```sh
~/Projects 🚀 luarocks install loadcaffe

Error: No results matching query were found.
```

I installed `torch` like they describe here: http://torch.ch/docs/getting-started.html.

**Comment by szagoruyko** [comment]
`brew rm lua` probably

**Comment by ngryman** [comment]
Still the same error :disappointed:

**Comment by szagoruyko** [comment]
see https://github.com/szagoruyko/loadcaffe/issues/48 https://github.com/szagoruyko/loadcaffe/issues/26 and https://github.com/szagoruyko/loadcaffe/issues/23 you need to make sure you call luarocks that comes with torch

**Comment by cyrusstoller** [comment]
I'm getting the following error message:

```bash
$ luarocks install loadcaffe
Installing https://raw.githubusercontent.com/torch/rocks/master/loadcaffe-1.0-0.rockspec...
Using https://raw.githubusercontent.com/torch/rocks/master/loadcaffe-1.0-0.rockspec... switching to 'build' mode
Cloning into 'loadcaffe'...
fatal: unable to connect to github.com:
github.com[0: 192.30.252.130]: errno=Operation timed out


Error: Failed cloning git repository.
```

**Comment by szagoruyko** [comment]
try `git config --global url."https://".insteadOf git://`

**Comment by cyrusstoller** [comment]
@szagoruyko Thanks! That seems to work

**Comment by jimrhoskins** [comment]
If you want a more surgical approach:

```sh
git config --global url."https://github.com/szagoruyko/loadcaffe.git".insteadof "git://github.com/szagoruyko/loadcaffe"
```

**Comment by boramalper** [comment]
> you need to make sure you call luarocks that comes with torch

I think this should be explicitly mentioned in the README.

**Comment by szagoruyko** [comment]
@boramalper good idea, thanks
