### ISSUE TITLE
how to add custom layer into loadcaffe

### ISSUE THREAD

**Issue by hermitman** [szagoruyko/loadcaffe#53]
Hi,

How can I add support of a custom layer?

The layer I want to have is the ROIPoolingLayer. (https://github.com/rbgirshick/caffe-fast-rcnn/tree/0dcd397b29507b8314e252e850518c5695efbb83)

Thanks,

**Comment by szagoruyko** [comment]
if you're looking for VOC Fast R-CNN models I have them converted here https://github.com/szagoruyko/fastrcnn-models.torch
If you want to load your own then you remove ROIPooling layer from prototxt, resave the model with caffe and load it with loadcaffe without this layer. Then you simply do a small surgery to make the networks look as in the link above.

**Comment by hermitman** [comment]
@szagoruyko I have a model trained with the ROIPooling and I need to load it into Torch. With your solution, what do you mean by "resave the model with caffe"?

Thanks,

**Comment by szagoruyko** [comment]
@hermitman well you can try without resaving, it never worked for me without resaving though. There is some story with caffe formats changing from fork to fork that I don't understand.
by resaving I mean you remove prototxt, open in caffe python, save with a different name.

**Comment by szagoruyko** [comment]
remove the line in prototxt I mean

**Comment by hermitman** [comment]
@szagoruyko I see. So, I need to use caffe to dump the network structure that it reads from the prototxt into a new one. I think I can settle with that solution.

On the other hand, I am not sure what to do to get the ROIPoolingLayer back into the Torch network. You mention that I should manually insert it. What do I do for it? I am new to Torch, so I am not clear about developing layers in Torch. 

Thanks,

**Comment by fmassa** [comment]
@hermitman there is an optimized `ROIPooling` layer here https://github.com/szagoruyko/imagine-nn.
To see how to insert the `ROIPooling` layer in your network, check for example https://github.com/fmassa/object-detection.torch/tree/refactoring#fast-rcnn

**Comment by hermitman** [comment]
@fmassa Awesome!!! I think I got all the references now.

Thanks @szagoruyko @fmassa
