### ISSUE TITLE
Can't get passed " require 'loadcaffe' "

### ISSUE THREAD

**Issue by Cirrusdreams** [szagoruyko/loadcaffe#54]
I'm trying to install loadcaffe along with torch7 (which I believe is installed correctly), but I can't get passed "require 'loadcaffe' " in the installation instructions for loadcaffe. I get the error "require: command not found". It seemed to like "luarocks install loadcaffe" worked properly. I am fairly new to the linux environment and github but a quick learner, please help me!

**Comment by szagoruyko** [comment]
did you type `th` before typing `require 'loadcaffe'`

**Comment by Cirrusdreams** [comment]
No! Will try!

**Comment by Cirrusdreams** [comment]
I had another error right away when running "model = loadcaffe.load('deploy.prototxt', 'bvlc_alexnet.caffemodel', 'ccn2')". It says "bash: syntax error near unexpected token `(' ". Maybe you can help me with that as well?
