### ISSUE TITLE
What version of lua does loadcaffe use?

### ISSUE THREAD

**Issue by jonobr1** [szagoruyko/loadcaffe#58]
I'm on a Mac and `brew install lua` which is currently on version `5.2.4_3`. When I `luarocks install loadcaffe` or `luarocks search loadcaffe` nothing comes up. This makes me think that loadcaffe works with an older version..? If so, which one should I use?

<img width="639" alt="screen shot 2016-03-24 at 10 07 31 am" src="https://cloud.githubusercontent.com/assets/220033/14024801/416df07a-f1a8-11e5-98a6-f611041e801e.png">

**Comment by szagoruyko** [comment]
remove lua and install torch http://torch.ch

**Comment by jonobr1** [comment]
Ohhhhhh! Thanks for the quick reply. I'll do that instead.

**Comment by jonobr1** [comment]
Worked like a charm. Thanks again for the quick response!
