### ISSUE TITLE
luarocks install loadcaffe : fails to build. Any idea?

### ISSUE THREAD

**Issue by kamalWam** [szagoruyko/loadcaffe#59]
Installing https://raw.githubusercontent.com/torch/rocks/master/loadcaffe-1.0-0.rockspec...
Using https://raw.githubusercontent.com/torch/rocks/master/loadcaffe-1.0-0.rockspec... switching to 'build' mode
Cloning into 'loadcaffe'...
remote: Counting objects: 18, done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 18 (delta 0), reused 6 (delta 0), pack-reused 0
Receiving objects: 100% (18/18), 18.86 KiB | 0 bytes/s, done.
Checking connectivity... done.
cmake -E make_directory build;
cd build;
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/Users/laptop/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/Users/laptop/torch/install/lib/luarocks/rocks/loadcaffe/1.0-0"; 
make
   
-- The C compiler identification is AppleClang 7.0.2.7000181
-- The CXX compiler identification is AppleClang 7.0.2.7000181
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Torch7 in /Users/laptop/torch/install
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Found PROTOBUF: /usr/local/lib/libprotobuf.dylib  
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/luarocks_loadcaffe-1.0-0-4495/loadcaffe/build
make[2]: *** No rule to make target `../PROTOBUF_PROTOC_EXECUTABLE-NOTFOUND', needed by `caffe.pb.cc'.  Stop.
make[1]: *** [CMakeFiles/loadcaffe.dir/all] Error 2
make: *** [all] Error 2

Error: Build error: Failed building.

**Comment by szagoruyko** [comment]
did you run `brew install protobuf`

**Comment by kamalWam** [comment]
brew install protobuf
Warning: protobuf-2.6.1 already installed, it's just not linked

It was already installed. Above it says: 

-- Found PROTOBUF: /usr/local/lib/libprotobuf.dylib


FYI:

gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin14.5.0
Thread model: posix

**Comment by szagoruyko** [comment]
`Warning: protobuf-2.6.1 already installed, it's just not linked` is a problem, do `brew link protobuf` or `brew doctor` something like that

**Comment by kamalWam** [comment]
I think issue was permissions:

brew link --overwrite protobuf
Linking /usr/local/Cellar/protobuf/2.6.1... 
Error: Could not symlink include/google/protobuf/compiler/cpp/cpp_generator.h
/usr/local/include/google/protobuf/compiler/cpp is not writable.


Managed to uninstall and update brew then reinstall.

Thanks.
