### ISSUE TITLE
luarocks install loadcaffe:  Error: No results matching query were found

### ISSUE THREAD

**Issue by timpulver** [szagoruyko/loadcaffe#61]
When trying to install loadcaffe I get the following error:

```
luarocks install loadcaffe

Error: No results matching query were found.
```

**Comment by szagoruyko** [comment]
install torch http://torch.ch
same as https://github.com/szagoruyko/loadcaffe/issues/48 and many other issues, sigh

**Comment by timpulver** [comment]
Sorry, I should have looked better. 
But if there are so many having this issue, the readme should be updated…

**Comment by szagoruyko** [comment]
@timpulver thanks for suggestion. I did that recently, the first 3 lines in readme say install torch7 in bold :)
