### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by JakeRyan1** [szagoruyko/loadcaffe#64]
I get the following error during installation:
No rule to make target `/usr/lib64/libopenblas.so', needed by `libloadcaffe.so'.  Stop.

**Comment by szagoruyko** [comment]
have you tried installing openblas?

**Comment by JakeRyan1** [comment]
Thanks. Openblas was missing on my lab server.

**Comment by CuriousCat-7** [comment]
I have the same problem with libopenblas-dev in my ubuntu16.04
