### ISSUE TITLE
No results matching query were found

### ISSUE THREAD

**Issue by FixerLT** [szagoruyko/loadcaffe#65]
After typing `luarocks install loadcaffe` i get:
`Warning: Failed searching manifest: Failed fetching manifest for https://raw.githubusercontent.com/torch/rocks/master - Failed downloading https://raw.githubusercontent.com/torch/rocks/master/manifest - /home/san/.cache/luarocks/https___raw.githubusercontent.com_torch_rocks_master/manifest
Warning: Failed searching manifest: Failed fetching manifest for https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master - Failed downloading https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/manifest - /home/san/.cache/luarocks/https___raw.githubusercontent.com_rocks-moonscript-org_moonrocks-mirror_master/manifest`

`Error: No results matching query were found.`

**Comment by szagoruyko** [comment]
@FixerLT did you install torch?

**Comment by FixerLT** [comment]
@szagoruyko Yes, i did.I was just following this guide: https://github.com/jcjohnson/neural-style/blob/master/INSTALL.md

**Comment by szagoruyko** [comment]
what happens when you do `luarocks install torch`

**Comment by osmankultur** [comment]
Good day Sir,
Tourch is installed but I could not able to install loadcaffe with using luarocks. Should I define a repo for loadcaffe. "luarocks install",  "luarocks list" commands are working.

osman@osman:~/DeepStyle/neural-style$ th
 
  ______             __   |  Torch7                                         
 /_  __/__  ________/ /   |  Scientific computing for Lua. 
  / / / _ \/ __/ __/ _ \  |  Type ? for help                                
 /_/  \___/_/  \__/_//_/  |  https://github.com/torch         
                          |  http://torch.ch                  
	
th> ^C
/home/osman/torch/install/bin/luajit: /home/osman/torch/install/share/lua/5.1/trepl/init.lua:585: interrupted!
stack traceback:
	/home/osman/torch/install/share/lua/5.1/trepl/init.lua:585: in function 'repl'
	...sman/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:199: in main chunk
	[C]: at 0x00405ea0
osman@osman:~/DeepStyle/neural-style$ sudo luarocks install loadcaffe

Error: No results matching query were found.
osman@osman:~/DeepStyle/neural-style$ sudo luarocks install torch

Error: No results matching query were found.
osman@osman:~/DeepStyle/neural-style$
osman@osman:~/DeepStyle/neural-style$ sudo luarocks list

Installed rocks:
----------------

alt-getopt
   0.7.0-1 (installed) - /home/osman/.luarocks/lib/luarocks/rocks

dkjson
   2.5-2 (installed) - /usr/local/lib/luarocks/rocks

lpeg
   1.0.0-1 (installed) - /home/osman/.luarocks/lib/luarocks/rocks

luafilesystem
   1.6.3-2 (installed) - /home/osman/.luarocks/lib/luarocks/rocks

moonscript
   0.4.0-1 (installed) - /home/osman/.luarocks/lib/luarocks/rocks

osman@osman:~/DeepStyle/neural-style$ sudo luarocks install loadcaffe

Error: No results matching query were found.
osman@osman:~/DeepStyle/neural-style$

Best Regards

**Comment by szagoruyko** [comment]
@osmankultur you are using system luarocks instead of the one that comes with torch.

**Comment by osmankultur** [comment]
@szagoruyko So, am I supposed to uninstall all luarocks packages and torch ? And then start over?

**Comment by szagoruyko** [comment]
@osmankultur normally system lua and torch can coexist, you'd just have to put ~/torch/install/bin path first in PATH, then the correct luarocks should be picked. First try using luarocks without sudo, if it does not work then remove system luarocks and try again, if it still does not work then yeah, try reinstalling everything

**Comment by FixerLT** [comment]
@szagoruyko `luarocks install torch
Warning: Failed searching manifest: Failed fetching manifest for https://raw.githubusercontent.com/torch/rocks/master - Failed downloading https://raw.githubusercontent.com/torch/rocks/master/manifest - /home/san/.cache/luarocks/https___raw.githubusercontent.com_torch_rocks_master/manifest
Warning: Failed searching manifest: Failed fetching manifest for https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master - Failed downloading https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/manifest - /home/san/.cache/luarocks/https___raw.githubusercontent.com_rocks-moonscript-org_moonrocks-mirror_master/manifest`

`Error: No results matching query were found.`

**Comment by szagoruyko** [comment]
@FixerLT you're using system luarocks too. this is unrelated to loadcaffe, closing.
