### ISSUE TITLE
loadcaffe installation issue with luarocks

### ISSUE THREAD

**Issue by huseyinozbey** [szagoruyko/loadcaffe#66]
Dear Sir,
I am getting issue while installing loadcaffe with luarocks. May I get your advice? How should I fix the error message "cc1plus: error: unrecognized command line option "-std=c++11"" ?

# luarocks install loadcaffe
Installing https://raw.githubusercontent.com/torch/rocks/master/loadcaffe-1.0-0.rockspec...
Using https://raw.githubusercontent.com/torch/rocks/master/loadcaffe-1.0-0.rockspec... switching to 'build' mode
Cloning into 'loadcaffe'...
remote: Counting objects: 18, done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 18 (delta 0), reused 6 (delta 0), pack-reused 0
Receiving objects: 100% (18/18), 18.86 KiB | 0 bytes/s, done.
Checking connectivity... done.
cmake -E make_directory build;
cd build;
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/share/apps/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/share/apps/torch/install/lib/luarocks/rocks/loadcaffe/1.0-0"; 
make
   
-- The C compiler identification is GNU 4.4.7
-- The CXX compiler identification is GNU 4.4.7
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Torch7 in /share/apps/torch/install
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found PROTOBUF: /usr/lib64/libprotobuf.so  
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/luarocks_loadcaffe-1.0-0-7087/loadcaffe/build
[ 25%] Running C++ protocol buffer compiler on caffe.proto
Scanning dependencies of target loadcaffe
[ 50%] Building CXX object CMakeFiles/loadcaffe.dir/loadcaffe.cpp.o
cc1plus: error: unrecognized command line option "-std=c++11"
make[2]: *** [CMakeFiles/loadcaffe.dir/loadcaffe.cpp.o] Error 1
make[1]: *** [CMakeFiles/loadcaffe.dir/all] Error 2
make: *** [all] Error 2

Error: Build error: Failed building.
#

Best regards

Huseyin Ozbey

**Comment by szagoruyko** [comment]
your compiler is too old. try installing a newer one or editing CMakeLists.txt to have `-std=c++0x` instead of `-std=c++11`

**Comment by iXYYL** [comment]
Dear szagoruyko, 
the error occured when it compiles the code which is cloned to "/tmp/luarocks_XXX" when I run "luarocks install loadcaffe"
how could I modify the CMakeLists.txt..?
could you help me to figure it out?
