### ISSUE TITLE
Loadcaffe Build Error

### ISSUE THREAD

**Issue by AdityaChaganti** [szagoruyko/loadcaffe#76]
Hey,

I can't figure out why I'm running into the build error when I execute 'luarocks install loadcaffe'. I already installed protobuf, and there were no issues there.

Installing https://raw.githubusercontent.com/torch/rocks/master/loadcaffe-1.0-0.rockspec...
Using https://raw.githubusercontent.com/torch/rocks/master/loadcaffe-1.0-0.rockspec... switching to 'build' mode
Cloning into 'loadcaffe'...
remote: Counting objects: 18, done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 18 (delta 0), reused 5 (delta 0), pack-reused 0
Receiving objects: 100% (18/18), 18.93 KiB | 0 bytes/s, done.
cmake -E make_directory build;
cd build;
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/home/adityac/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/home/adityac/torch/install/lib/luarocks/rocks/loadcaffe/1.0-0"; 
make
   
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found Torch7 in /home/adityac/torch/install
-- Could NOT find PROTOBUF (missing:  PROTOBUF_LIBRARY PROTOBUF_INCLUDE_DIR) 
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
PROTOBUF_LIBRARY (ADVANCED)
    linked by target "loadcaffe" in directory /tmp/luarocks_loadcaffe-1.0-0-7097/loadcaffe

-- Configuring incomplete, errors occurred!
make: *** No targets specified and no makefile found.  Stop.

Error: Build error: Failed building.

Any help here?

**Comment by szagoruyko** [comment]
did you install protobuf:
```
sudo apt-get install libprotobuf-dev protobuf-compiler
```

**Comment by AdityaChaganti** [comment]
@szagoruyko : I'm on a Red-Hat server, so I did this:

sudo yum install libprotobuf-dev protobuf-compiler
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: linux.cc.lehigh.edu
 * epel: mirror.us.leaseweb.net
 * extras: mirrors.advancedhosters.com
 * updates: mirrors.lga7.us.voxel.net
No package libprotobuf-dev available.
Package protobuf-compiler-2.5.0-8.el7.x86_64 already installed and latest version
Nothing to do

**Comment by szagoruyko** [comment]
you still need protobuf header files. check on protobuf page how to install it.

**Comment by AdityaChaganti** [comment]
Thank you! Figured this out by following the instructions here:

https://leveragebigdata.wordpress.com/2015/10/08/install-protocol-buffer-2-5-0/

**Comment by YuanEZhou** [comment]
I encounter the same problem. And I try **_sudo apt-get install libprotobuf-dev protobuf-compiler_**, but it doesn't work.
Finally, I fix it by  **_conda install -c anaconda protobuf_** 
I think this problem is caused because I install Anaconda and put it into my PATH.
