### ISSUE TITLE
is there any way to install loadcaffe from source without github access?

### ISSUE THREAD

**Issue by iXYYL** [szagoruyko/loadcaffe#88]
Dear sir,

I have been blocked by the internet connection for almost one week..
due to the poor policy, I have no right to access github.com over the server machine,
and I didn't find any info about how to install loadcaffe from source...
even I tried to upload all repo source to the server machine manually,
and install loadcaffe using "luarocks install loadcaffe-1.0-0.rockspec",
it still went to github for a Git repository...

`luarocks install loadcaffe-1.0-0.rockspec 
Using loadcaffe-1.0-0.rockspec... switching to 'build' mode
Initialized empty Git repository in /tmp/luarocks_loadcaffe-1.0-0-7877/loadcaffe/.git/
github.com[0: 192.30.253.112]: errno=Connection timed out`

**Comment by szagoruyko** [comment]
yes, you can do:
```
git clone https://github.com/szagoruyko/loadcaffe
cd loadcaffe
luarocks make
```
you can download zip archive with the code and move it to the machine without github access

**Comment by iXYYL** [comment]
Great! thanks to @szagoruyko 
Best Regards!

**Comment by MagaretJi** [comment]
but  it still occurs error.....
[root@node12 loadcaffe]# luarocks make
cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/home/laibin/torch3.0/install/bin/.." -DCMAKE_INSTALL_PREFIX="/home/laibin/torch3.0/install/lib/luarocks/rocks/loadcaffe/1.0-0" && make
   
-- Found Torch7 in /home/laibin/torch3.0/install
-- Could NOT find PROTOBUF (missing:  PROTOBUF_LIBRARY PROTOBUF_INCLUDE_DIR) 
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
PROTOBUF_LIBRARY (ADVANCED)
    linked by target "loadcaffe" in directory /home/laibin/load_caffe191223/loadcaffe

-- Configuring incomplete, errors occurred!
See also "/home/laibin/load_caffe191223/loadcaffe/build/CMakeFiles/CMakeOutput.log".
See also "/home/laibin/load_caffe191223/loadcaffe/build/CMakeFiles/CMakeError.log".

Error: Build error: Failed building.

**Comment by MagaretJi** [comment]
> 是的，您可以执行以下操作：
> 
> ```
> git clone https://github.com/szagoruyko/loadcaffe
> cd loadcaffe
> luarocks make
> ```
> 
> 您可以使用代码下载zip归档文件，然后将其移动到没有github访问权限的机器上

but it still occurs error.....
[root@node12 loadcaffe]# luarocks make
cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/home/laibin/torch3.0/install/bin/.." -DCMAKE_INSTALL_PREFIX="/home/laibin/torch3.0/install/lib/luarocks/rocks/loadcaffe/1.0-0" && make

-- Found Torch7 in /home/laibin/torch3.0/install
-- Could NOT find PROTOBUF (missing: PROTOBUF_LIBRARY PROTOBUF_INCLUDE_DIR)
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
PROTOBUF_LIBRARY (ADVANCED)
linked by target "loadcaffe" in directory /home/laibin/load_caffe191223/loadcaffe

-- Configuring incomplete, errors occurred!
See also "/home/laibin/load_caffe191223/loadcaffe/build/CMakeFiles/CMakeOutput.log".
See also "/home/laibin/load_caffe191223/loadcaffe/build/CMakeFiles/CMakeError.log".

Error: Build error: Failed building.
