### ISSUE TITLE
Load a torch model without loading binary data

### ISSUE THREAD

**Issue by Alexis-Jacob** [szagoruyko/loadcaffe#9]
I would like to use loadcaffe without having the binary file.
When I tried to change a bit the code such as 

```
caffe::NetParameter* netparam = new caffe::NetParameter();
 bool success = ReadProtoFromTextFile(prototxt_name, netparam);
//bool success = ReadProtoFromBinaryFile(binary_name, netparam);
```
then  I check the number of layer with 
```
std::cout << netparam->layers_size() << std::endl;
```
but I'm always getting a size of 0 

Thanks for your help

**Comment by szagoruyko** [comment]
which network do you try to load?

**Comment by Alexis-Jacob** [comment]
alexnet 
https://github.com/BVLC/caffe/tree/master/models/bvlc_alexnet

**Comment by szagoruyko** [comment]
try with ```netparam->layer_size()```, "layers" is deprecated but contained in old binaries, as I understand.

**Comment by Alexis-Jacob** [comment]
With ```layer_size()``` I have the correct value.
However after that when the ```convertProtoToLua``` is called I get a segfault at : 
``` 
auto& layer = netparam.layers(i);
```

**Comment by szagoruyko** [comment]
that's because you don't have any layers. All the layers are in ```layer(i)```, but convertProtoToLua won't work with it anyways. It's written for V1 layers.
In fact this is a main issue with loadcaffe, it doesn't work with nets saved with V2 ```layer```.

**Comment by Alexis-Jacob** [comment]
Okay,  thanks for your explanation
