### ISSUE TITLE
Luarocks install loadcaffe doesn't work, how to install offline?

### ISSUE THREAD

**Issue by Naruto-Sasuke** [szagoruyko/loadcaffe#95]
`user@user-ubuntu:~$ luarocks install loadcaffe 
Warning: Failed searching manifest: Failed fetching manifest for https://raw.githubusercontent.com/torch/rocks/master - Failed downloading https://raw.githubusercontent.com/torch/rocks/master/manifest - /home/user/.cache/luarocks/https___raw.githubusercontent.com_torch_rocks_master/manifest`
I have tried dozens of times, however, it still doesn't work . Is there a way to get it installed offline?

**Comment by xiangcong** [comment]
hi~how do you solve the problem?
