### ISSUE TITLE
VGG ILSVRC-2014 19-layer. Each time different output results for the same image.

### ISSUE THREAD

**Issue by viktorheli** [szagoruyko/loadcaffe#96]
My test lua script:

require 'paths'
require 'image'
require 'nn'
require 'loadcaffe'
require 'cudnn'
require 'ccn2'

--torch.setdefaulttensortype('torch.FloatTensor')

--cmd line arg
cmd = torch.CmdLine()
cmd:text()
cmd:text('Image Classification')
cmd:text('Example:')
cmd:text('$> th classify.lua -img youimage.jpg -net')
cmd:text('Options:')
cmd:option('-img', 'none', 'path to image')
cmd:option('-imgdisp', 'no', 'Dataset to train network')

opt = cmd:parse(arg or {})

--round function

function round(num, numDecimalPlaces)
  return tonumber(string.format("%." .. (numDecimalPlaces or 0) .. "f", num))
end

--dimensions of image
imgheight = 224

imgwidth = 224

   if (paths.filep(opt.img) == true and paths.filep(opt.net) ) then

--              net = torch.load(opt.net)
--              net = loadcaffe.load('VGG_ILSVRC_16_layers_deploy.prototxt', 'VGG_ILSVRC_16_layers.caffemodel', 'nn')

                net = loadcaffe.load('VGG_ILSVRC_19_layers_deploy.prototxt', 'VGG_ILSVRC_19_layers.caffemodel', 'cudnn')

--              print(net)
                img = opt.img
                load = image.load(img, 3, float)

                imgscaled = image.scale(load, imgwidth, imgheight)

                --to torch tensor
                imgdata = torch.Tensor(imgscaled,3, imgwidth, imgheight):cuda()

                --forward image through net
                predict = net:forward(imgdata):cuda()

                predicted = predict

--              print(predicted)
                for i=1,predicted:size(1) do

--                        print(round(predicted[i],5)*100)
                        if predicted[i] > 0.001 then
                                print("Category number: "..i.." Probability:  "..predicted[i])
                        end
                end

                if (opt.imgdisp == "yes" ) then
                        image.display(imgscaled)
                        --print (predicted)
                        collectgarbage()
                end
                else
                      print("Warning!!! No image or pretrained model found!")

        end
 
Runnig script:
th classify.lua -img 309007341_5471ee47fe.jpg

First start: 
th classify.lua -img 309007341_5471ee47fe.jpg

Category number: 966 Probability:  0.001122118672356
Category number: 1000 Probability:  0.012724352069199

Second start:
th classify.lua -img 309007341_5471ee47fe.jpg

Category number: 966 Probability:  0.0010504205711186
Category number: 1000 Probability:  0.017033163458109

Check how the model works in the Сaffe no possibility. 

I tried to load a model with ccn2, nn, cudnn - the result does not change.
I can not understand the problem in the loadcaffe or in the model itself.

At start I receive the warning from google protobuf, but all works:

[libprotobuf WARNING google/protobuf/io/coded_stream.cc:604] Reading dangerously large protocol message.  If the message turns out to be larger than 1073741824 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:81] The total number of bytes read was 574671192
Successfully loaded VGG_ILSVRC_19_layers.caffemodel
conv1_1: 64 3 3 3
conv1_2: 64 64 3 3
conv2_1: 128 64 3 3
conv2_2: 128 128 3 3
conv3_1: 256 128 3 3
conv3_2: 256 256 3 3
conv3_3: 256 256 3 3
conv3_4: 256 256 3 3
conv4_1: 512 256 3 3
conv4_2: 512 512 3 3
conv4_3: 512 512 3 3
conv4_4: 512 512 3 3
conv5_1: 512 512 3 3
conv5_2: 512 512 3 3
conv5_3: 512 512 3 3
conv5_4: 512 512 3 3
fc6: 1 1 25088 4096
fc7: 1 1 4096 4096
fc8: 1 1 4096 1000

**Comment by ShowLang** [comment]
maybe you should add `net:evaluation()` before predict

**Comment by viktorheli** [comment]
Yes! It's work. Thanks!

**Comment by viktorheli** [comment]
ShowLang, hi! I'm sorry for question. But I do not find any docs for net:evaluation() function. Can you help me with it? 
Thanks.
