### ISSUE TITLE
Why Do We Need to Provide a .caffemodel file?

### ISSUE THREAD

**Issue by RishabhMalviya** [szagoruyko/loadcaffe#98]
From what I understand, the `.prototxt` files adequately describe the network architecture. The `.caffemodel` files simply define the internal states of the parameters/gradients of those layers.

Is there some way to create a torch network using just the `.prototxt` file; the created network would mimic the network architecture, but everything would be initialized to default values (sampled randomly from gaussians or whatever happens to be the standard procedure)?

**Comment by szagoruyko** [comment]
well, actually, loadcaffe only uses `.caffemodel` and completely ignores `.prototxt`

**Comment by RishabhMalviya** [comment]
So, is there any quick way to create a 'dummy' `.caffemodel` from a given `.prototxt`?

**Comment by RishabhMalviya** [comment]
Okay, I've tried to make some changes to loadcaffe.cpp to get it to read everything from the `.prototxt` file. I do the following after `cd`ing into the loadcaffe directory:
```
mkdir build
cd ./build
cmake ../
make
```

Running `make` gives me the following error:
```
/home/rishabh/code/loadcaffe/loadcaffe.cpp:32:28: fatal error: build/caffe.pb.h: No such file or directory
compilation terminated.
CMakeFiles/loadcaffe.dir/build.make:70: recipe for target 'CMakeFiles/loadcaffe.dir/loadcaffe.cpp.o' failed
make[2]: *** [CMakeFiles/loadcaffe.dir/loadcaffe.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/loadcaffe.dir/all' failed
make[1]: *** [CMakeFiles/loadcaffe.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

There is now a `caffe.pb.h` file in the build directory I created, though. Despite this, running `make` again causes the same error.

**Comment by RishabhMalviya** [comment]
Also, after running `make`, the C libraries will get installed, right?

Can I now just run `luarock install loadcaffe-1.0-0.rockspec` to make the changes reflect in the Lua command `loadcaffe.load(...`?

**Comment by RishabhMalviya** [comment]
Any help is appreciated.

Basically, i just need to know how to compile changes I make in the file `loadcaffe.cpp` so that I can at least test them.
